manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: pmw3610
      url-base: https://github.com/kaievns
    - name: mouse-behaviours
      url-base: https://github.com/kaievns

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-with-input-processors
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: pmw3610
      revision: main
    - name: input-shaping
      remote: zmk-mouse-behaviours
      revision: main
  self:
    path: config
